name: CCFinderX Clone Detection

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:   # allows manual run from Actions tab

jobs:
  run-ccfinderx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            autoconf \
            automake \
            libtool \
            libboost-all-dev \
            libicu-dev \
            python2.7-dev \
            wget \
            unzip

      - name: Clone CCFinderX repository
        run: |
          git clone https://github.com/gpoo/ccfinderx.git
          cd ccfinderx
          libtoolize
          aclocal -I m4 --install
          autoconf
          automake --foreign --add-missing
          ./configure
          make

      - name: Build GemX (GUI)
        run: |
          cd ccfinderx/GemX
          make

      - name: Run CCFinderX on DuckSimulator
        run: |
          cd ccfinderx
          ./ccfx/ccfx d java ../DuckSimulator -o result.ccfxd
          ./ccfx/ccfx p result.ccfxd -o result.txt
          cat result.txt

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: ccfinderx-report
          path: result.txt
