name: CCFinderX

on:
  push:
    branches: [ main ]
  workflow_dispatch:   # manual run

jobs:
  run-ccfinderx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mono-complete unzip wget

      - name: Download CCFinderX prebuilt binary
        run: |
          wget https://github.com/gpoo/ccfinderx/releases/download/v1.0/ccfx.zip
          unzip ccfx.zip -d ccfx
          chmod +x ccfx/ccfx

      - name: Run CCFinderX (Java)
        run: |
          ./ccfx/ccfx d java ./ -o result.ccfxd
          ./ccfx/ccfx p result.ccfxd -o result.txt
          cat result.txt

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: ccfinderx-report
          path: result.txt
