name: CCFinderX

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:   # allows manual run from Actions tab

jobs:
  run-ccfinderx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run CCFinderX using GitHub Action
        uses: gpoo/ccfinderx-action@v1
        with:
          path: ./   # scan the whole DuckSimulator project
          output: result.txt

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: ccfinderx-report
          path: result.txt
